### ISSUE TITLE
BUG: npm WARN twitchbotstream@x.x.x No repository field.

### ISSUE THREAD

**Issue by Aqwa1234** [volca780/TwitchBotStream#1]
quand j'essaye de mettre npm install sur le cmder il me dit : 

C:\Users\Responsable\Desktop\TwitchBotStream-master  (twitchbotstream@1.0.0)
λ npm install
npm WARN twitchbotstream@1.0.0 No repository field.

pourtant j'ai bien nodejs d'installer j'ai tout essayer mais rien a faire, merci de votre aide.

**Comment by hichxm** [comment]
essaie de supprimer le dossier node_module et de retaper la commande ``` npm install ```

**Comment by Aqwa1234** [comment]
sa a marcher merci
